import JSLib from "../SproutCore/lib.js";

const snips = [
  // Python keywords
  "import", "global",
  "class", "def",
  "pass",
  "for", "while", "break", "continue",
  "if", "elif", "else",
  "and", "or", "not",
  "True", "False", "None",
  "async", "await",
  "is", "in", "with",

  // Special functions
  "super()",
  "hasattr(obj, \"foo\")",
  "min", "max",

  // Standard libraries
  "SproutCore",
  "JSLib",
  "pyodide",
  "game",
  "input",
  "random()",
  "math", "math.sin", "math.cos", "math.pi",
  "math.sqrt", "math.ceil", "math.floor",
  "math.asin", "math.acos", "math.atan", "math.atan2",
  "math.sinh", "math.cosh", "math.tanh",
  "math.asinh", "math.acosh", "math.atanh",
  "math.dist", "math.e", "math.exp", "math.pow",
  "math.fabs", "math.gcd",
  "math.hypot", "math.isfinite",
  "math.isinf", "math.isnan",
  "math.lcm", "math.log", "math.log10", "math.log2",
  "math.modf", "math.perm", "math.pow", "math.prod",
  "math.remainder", "math.sumprod",
  "math.inf", "math.nan", "math.tau",
  "math.trunc",

  // Pylib classes
  "game.entity", "game.entity.LivingEntity",
  "game.entity.UIEntity",
  "game.entity.BulletEntity",
  "game.entity.EntityWeapon",
  "game.entity.ExplodingBulletEntity",
  "game.entity.LanceEntity",
  "game.entity.ExplosionEntity",
  "game.asset",
  "game.asset.ImageAsset",
  "game.asset.AnimImageAsset",
  "game.asset.SubImageAsset",

  "AutoUpdateUtil",
  "AutoUpdateUtil.TimerUtil",
  "AutoUpdateUtil.SmoothUtil",
  "AutoUpdateUtil.RandTimerUtil",
  "AutoUpdateUtil.VerletUtil",

  // Snippets
  "import math",
  ["import random...", "from random import random"],
  ["class...", `class MyClass():\n  def __init__(this):\n    # super().__init__()\n    this.foo = "bar"`],
  // ["classwith...", `class MyClass():\n  def __init__(this):\n    # super().__init__()\n    this.foo = "bar"\n  def __enter__(this):\n    return this\n\n  def __exit__(this, exc_type, exc, tb):\n    pass\n`],
  ["for...", `for i in range(0,10):\n  `],
  ["if else...", `if condition:\n  pass\nelse:\n  pass`],
  ["if elif else...", `if condition:\n  pass\nelif condition:\n  pass\nelse:\n  pass`],
  ["def fn()...", `def myFunction():\n  pass`],
  ["match cases...", `match myVar:\n  case value:\n    pass\n  case _:\n    pass #default case`],
  ["try...", `try:\n  pass\nexcept Exception:\n  pass\nelse:\n  pass\nfinally:\n  pass`],
  ["with...", `with MyClass() as v:\n  pass`],
  ["lambda...", `lambda x : x + 10`],
  ["lambda3...", `lambda x, y, z: x*x + y*y + z*z`],

  // Library snippets
  ["import bullets...", `from pylib.bullets import BulletEntity, EntityWeapon, ExplodingBulletEntity, LanceEntity`],
  ["import autoutils...", `from pylib.autoutil import AutoUpdateUtil, TimerUtil, SmoothUtil, RandTimerUtil, VerletUtil`],
  ["import entities...", `from pylib.entity import Entity, LivingEntity, TurtleEntity, UIEntity`],
  ["import game...", `from pylib.game import GameClass\nfrom pylib.state import GameState`],
  ["import default...", `from pylib.games.shooter import game`],
  ["timer...", `AutoUpdateUtil.TimerUtil(myfunction, 1, repeats=True)`],
  "timer.stop()", "timer.start()", "timer.resume()", "timer.reset()", "timer.sustain()",
  ["randtimer...", `AutoUpdateUtil.RandTimerUtil(myfunction, minInterval=0, maxInterval=1, repeats=True)`],

  // Custom snippets
  "def load():",
  "def update(dt):",
  "def draw():",
  "def keyDown(key):",
  "def keyUp(key):",
  "def mouseDown(b, x, y)",
  "def mouseUp(b, x, y)",
  "def entityClick(entity, button, x, y)",
  "SmoothUtil(val, min, max, time)",
  "foo = property(__get_foo__, __set_foo__, __del_foo__, \"description\")",
  "SproutCore.graphics.width",
  "SproutCore.graphics.height",
  "SproutCore.graphics.draw(sprite, x, y, sx, sy)",
  "SproutCore.Asset.ImageAsset.getImage(\"error.png\")",
  
  // Accursed pyodide snippets
  "pyodide.code.run_js('''() => {}''')()",
  "pyodide.ffi.create_proxy()",
  
  // Game instance snippets
  "game.world",
  "game.keyState(\"ArrowUp\")",

  // Entity instance snippets
  "entity.unitid", "entity.age",
  "entity.drawDebug = False",
  "entity.scalex = 1",
  "entity.scaley = 1",
  "entity.autoscale = False",
  "entity.lifetime = -1",
  "entity.team = \"none\"",
  "entity.verlet = False",
  "entity.gravity = False",
  "entity.angle = 0",
  "entity.x = 0",
  "entity.y = 0",
  "entity.w", "entity.h", "entity.r",
  "entity.collision_type",
  "entity.scale = 1",
  "entity.body = SproutCore.Geo.Circle.new(0, 0, 0)",
  "entity.sprite = SproutCore.Asset.ImageAsset.getImage(\"error.png\")",
  "entity.hidden = False",
  "entity.update(dt)",
  "entity.touch(other)",
  "entity.delete(\"reason\")",
  "entity.intersects(other)",
  "entity.draw()",
  "entity.forward(1)",
  "entity.backward(1)",
  "entity.left(1)",
  "entity.right(1)",
  "entity.move(1, 1)",
  "entity.rotate(180)",
  "entity.turnLeft(90)",
  "entity.turnRight(90)",
  "livingEntity.damage(1)",
  "livingEntity.speed = 300",
  "livingEntity.health = 100",
  "livingEntity.attack = 10",
  "livingEntity.contained = False",
  "livingEntity.shoot(Entity.BulletEntity, 0, 0, 0)",

  // Turtle instance snippets
  "turtle.forward(1)",
  "turtle.backward(1)",
  "turtle.left(1)",
  "turtle.right(1)",
  "turtle.move(1, 1)",
  "turtle.turnLeft(90)",
  "turtle.turnRight(90)",
  "turtle.rotate(180)",
  "turtle.setPosition(0, 0)",
  "turtle.setHeading(0)",
  "turtle.beginFill(\"#2f4f4f\")",
  "turtle.endFill()",
  "turtle.penUp()",
  "turtle.penDown()",
  "turtle.lineColor = \"#2f4f4f\"",
  "turtle.fillColor = \"#2f4f4f\"",
  "turtle.penWidth = 1",
  "turtle.delay = 0",
  "turtle.sprite = SproutCore.Asset.ImageAsset.getImage(\"turtle\")",

  // Asset snippets
  "SproutCore.Asset.getAsset(\"src\")",
  "SproutCore.Asset.ImageAsset.getImage(\"src.png\", \"src\", True)",
  "SproutCore.Asset.AnimImageAsset.getImage(\"src.png\", \"src\", True)",
  "animImage.slice(x, y, w, h, dx, dy)",
  "animImage.autoSlice(x, y, hSlices, vSlices, dx, dy)",
  "SproutCore.Asset.SubImageAsset.getImage(\"src.png\", \"src\", True, x, y, w, h)",
  '"enemy_base"', '"enemy_debris_1"', '"helicopter"', '"heliblades"',
  '"heliblades_spin"', '"player_base"', '"player_gold"', '"player_red"',
  '"player_skull"', '"bullet_base"', '"bullet_rocket"', '"bullet_plasma"',
  '"bg0"', '"bg1"', '"turtle"', '"splode"', '"lance"', '"bullet_bright"',
  '"shield"', '"rockhand"', '"paperhand"', '"scissorshand"',
  '"rock"', '"paper"', '"scissors"',
];
for (let i = 0; i < snips.length; i++) {
  const snip = snips[i];
  if (!JSLib.isString(snip)) {
    snips[i] = {
      name: snip[0],
      value: JSLib.isString(snip[1]) ? snip[1] : snip[0],
      score: 1000
    };
  }
}
export default snips;